### ISSUE TITLE
Homebridge plugin

### ISSUE THREAD

**Issue by xrust83** [opravdin/weback-unofficial#13]
Hello. I used your app on Home Assistant, it worked great and even dumped the vacuum into HomeKit. Several months ago I switched to Homebridge and unfortunately there is no alternative there. The vacuum cleaner is very popular with tens of thousands of sales. Could you develop a full-fledged application for Homebridge or only mqtt commands for Homebridge so that later you could use for example the Homebridge Mqttthing plugin

**Comment by opravdin** [comment]
I am not familiar with NodeJS (which is what homebridge based on) and I am not a user of homebridge itself. By the way, my package is enough documented to be ported on another programming language (especially if it has Amazon's API client). I don't have this port in plans.

**Comment by marcelkordek** [comment]
Hey, i have ported the code to JavaScript and released a Plugin for Homebridge.

-> homebridge-tesvor

@opravdin thanks for your work!

greetings
Marcel

**Comment by xrust83** [comment]
> Hey, i have ported the code to JavaScript and released a Plugin for Homebridge.
> 
> -> homebridge-tesvor
> 
> @opravdin thanks for your work!
> 
> greetings
> Marcel

Thank you very much for unsubscribing about this. This is very relevant to me. I have already installed your plugin
