### ISSUE TITLE
"account or password is incorrect" during auth

### ISSUE THREAD

**Issue by PRabahy** [opravdin/weback-unofficial#2]
Hi,

I have tried several times to authenticate and keep getting problems. At first I had a very long complex password, so I used the Weback app to change it. I now have a 12 character alpha numeric password password associated with my email address and it is still giving me "account or password is incorrect". I am almost 100% sure that this is correct because I hand typed it on my my phone and in the python script. I was nervous that copy pasting was introducing invisible characters.

Any ideas? Has this been confirmed to work with email? All of the examples show a phone number.

**Comment by PRabahy** [comment]
I'm guessing this is related to https://community.home-assistant.io/t/weback-cloud-integration-testers-and-help-required/186155/12.

**Comment by PRabahy** [comment]
I believe that https://github.com/opravdin/weback-unofficial/pull/1 fixes this. It might still call for an update to the documentation.

**Comment by opravdin** [comment]
For email login use +1-email@email.com format. I will add region selection in future updates
