### ISSUE TITLE
SSL validation failed

### ISSUE THREAD

**Issue by ajmorris1** [opravdin/weback-unofficial#5]
SSL certificate verification is failing:
botocore.exceptions.SSLError: SSL validation failed for https://cognito-identity.ap-southeast-1.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

I have tried to set no ssl verify in the aws call to no avail. Does anyone know how to fix this issue?

**Comment by opravdin** [comment]
I think this is caused by your local environment (maybe some proxy trying to decrypt traffic or like that)
